(() => {
const phone='917397559527';
const services={
A:{label:'AI POWERED',title:'Yes, I create with AI.',description:'AI posters, videos and practical automation built for business.',message:'Hi Prakash, I am interested in AI content or automation.'},
B:{label:'BRAND IDENTITY',title:'Yes, I build brands.',description:'Clear visual identities and brand systems people remember.',message:'Hi Prakash, I need help with branding.'},
C:{label:'CONTENT CREATION',title:'Yes, I create content.',description:'Useful content strategies, copy and campaigns that earn attention.',message:'Hi Prakash, I need content creation support.'},
D:{label:'DIGITAL DESIGN',title:'Yes, I design.',description:'Professional digital creatives, campaign visuals and social graphics.',message:'Hi Prakash, I need digital design support.'},
E:{label:'EMAIL MARKETING',title:'Yes, I build email campaigns.',description:'Focused email content that nurtures interest and drives action.',message:'Hi Prakash, I want to discuss email marketing.'},
G:{label:'GOOGLE PRESENCE',title:'Yes, I help you get found.',description:'Google Business Profile support and search-ready digital foundations.',message:'Hi Prakash, I need help improving my Google presence.'},
M:{label:'SOCIAL MEDIA',title:'Yes, I manage social media.',description:'Planning, publishing and creative management for consistent growth.',message:'Hi Prakash, I need social media management.'},
R:{label:'REELS & SHORT VIDEO',title:'Yes, I create reels.',description:'Short-form video concepts and edits designed to stop the scroll.',message:'Hi Prakash, I need reels and short videos.'},
S:{label:'SEARCH VISIBILITY',title:'Yes, I do SEO.',description:'Search-friendly websites and content that help customers discover you.',message:'Hi Prakash, I need SEO support.'},
V:{label:'AI VIDEO',title:'Yes, I create AI videos.',description:'Distinctive AI-assisted promotional videos made for your brand.',message:'Hi Prakash, I am interested in AI video creation.'},
W:{label:'WEB DEVELOPMENT',title:'Yes, I build websites.',description:'Fast, mobile-friendly websites designed to turn visits into enquiries.',message:'Hi Prakash, I would like to build a website.'},
P:{label:'PHONE',title:'Call Prakash.',description:'+91 73975 59527 — let’s talk about what your business needs.',action:'CALL NOW ↗',href:'tel:+917397559527',event:'call_click'},
L:{label:'LOCATIONS',title:'Pondicherry. Bangalore. Chennai.',description:'Available for local businesses and remote projects everywhere.',message:'Hi Prakash, I would like to discuss a project in my city.'}};
const grid=document.querySelector('#keyGrid'),content=document.querySelector('#screenContent'),display=document.querySelector('#keyDisplay'),label=document.querySelector('#screenLabel'),title=document.querySelector('#screenTitle'),description=document.querySelector('#screenDescription'),action=document.querySelector('#screenAction'),bootLayer=document.querySelector('#bootLayer'),bootNumber=document.querySelector('#bootNumber'),bootProgress=document.querySelector('#bootProgress'),bootMessage=document.querySelector('#bootMessage');
let systemReady=false;
const desktop=document.querySelector('#desktopLayer'),osWindow=document.querySelector('#osWindow'),windowTitle=document.querySelector('#windowTitle'),windowBody=document.querySelector('#windowBody'),windowBar=document.querySelector('#windowBar');
const apps={
services:{title:'SERVICES',html:'<div class="app-kicker">WHAT I BUILD</div><h2>Digital tools that move businesses.</h2><div class="service-list"><button data-service="W">W <span>Web Development</span></button><button data-service="M">M <span>Social Media</span></button><button data-service="C">C <span>Content Marketing</span></button><button data-service="B">B <span>Branding</span></button><button data-service="A">A <span>AI Content</span></button><button data-service="S">S <span>SEO</span></button></div>'},
projects:{title:'PROJECTS',html:'<div class="app-kicker">SELECTED WORK</div><h2>Built for real-world use.</h2><div class="project-list"><a href="https://tamil-nadu-crime-monitor-hazel.vercel.app/" target="_blank" rel="noopener" data-project="Tamil Nadu Crime Monitor"><strong>Tamil Nadu Crime Monitor</strong><span>Public data dashboard ↗</span></a><a href="https://newsfive.in/" target="_blank" rel="noopener" data-project="NewsFive"><strong>NewsFive</strong><span>Digital news platform ↗</span></a></div>'},
about:{title:'ABOUT PRAKASH',html:'<div class="about-app"><div class="avatar">PR</div><div><div class="app-kicker">CREATIVE DEVELOPER · DIGITAL MARKETER</div><h2>Prakash Ravikumar</h2><p>I combine technology, creativity and marketing to help businesses grow digitally.</p><strong>Pondicherry · Bangalore · Chennai</strong></div></div>'},
contact:{title:'START A PROJECT',html:'<div class="app-kicker">DIRECT CONTACT</div><h2>Ready to move your business forward?</h2><div class="contact-app"><a href="https://wa.me/917397559527?text=Hi%20Prakash%2C%20I%20would%20like%20to%20start%20a%20project." target="_blank" rel="noopener" data-contact="whatsapp">WHATSAPP ME ↗</a><a href="tel:+917397559527" data-contact="call">CALL 73975 59527 ↗</a></div>'}
};
function track(name,details={}){window.dataLayer=window.dataLayer||[];window.dataLayer.push({event:name,...details})}
function selectKey(rawKey){if(!systemReady)return;const key=rawKey.toUpperCase();if(!/^[A-Z]$/.test(key))return;const item=services[key];const pressed=document.querySelector(`[data-key="${key}"]`);if(pressed){pressed.classList.remove('pressed');void pressed.offsetWidth;pressed.classList.add('pressed');setTimeout(()=>pressed.classList.remove('pressed'),220)}document.querySelectorAll('[data-key]').forEach(b=>b.classList.toggle('active',b.dataset.key===key));content.classList.add('changing');setTimeout(()=>{display.textContent=key;if(item){label.textContent=item.label;title.textContent=item.title;description.textContent=item.description;action.textContent=item.action||'START A CONVERSATION ↗';action.href=item.href||`https://wa.me/${phone}?text=${encodeURIComponent(item.message)}`;action.target=item.href?'':'_blank';action.rel=item.href?'':'noopener';action.dataset.event=item.event||'whatsapp_click';track('service_key_selected',{key,service:item.label})}else{label.textContent='NO MATCH FOUND';title.textContent='Sorry, no matching service found.';description.textContent='Try W, S, C, D, M, A, P or L—or tell me what you need on WhatsApp.';action.textContent='ASK PRAKASH ↗';action.href=`https://wa.me/${phone}?text=${encodeURIComponent('Hi Prakash, I need a digital service and would like to know if you can help.')}`;action.target='_blank';action.rel='noopener';action.dataset.event='whatsapp_click';track('no_match_key',{key})}action.classList.remove('hidden');content.classList.remove('changing')},160)}
const keyboardRows=[
  [{t:'esc',w:1.2},'F1','F2','F3','F4','F5','F6','F7','F8','F9','F10','F11','F12',{t:'del',w:1.2}],
  ['`','1','2','3','4','5','6','7','8','9','0','-','=',{t:'backspace',w:2}],
  [{t:'tab',w:1.5},'Q','W','E','R','T','Y','U','I','O','P','[',']',{t:'\\',w:1.5}],
  [{t:'caps',w:1.8},'A','S','D','F','G','H','J','K','L',';',{t:"'"},{t:'enter',w:2.2}],
  [{t:'shift',w:2.2},'Z','X','C','V','B','N','M',',','.','/',{t:'shift',w:2.7}],
  [{t:'ctrl',w:1.3},{t:'fn',w:1.1},{t:'⊞',w:1.1},{t:'alt',w:1.2},{t:'',w:6},{t:'alt',w:1.2},{t:'ctrl',w:1.2},{t:'◀',w:1},{t:'▲▼',w:1},{t:'▶',w:1}]
];
keyboardRows.forEach((row,rowIndex)=>{const rowElement=document.createElement('div');rowElement.className=`key-row row-${rowIndex+1}`;row.forEach(item=>{const config=typeof item==='string'?{t:item}:item;const key=config.t;const b=document.createElement('button');b.type='button';b.textContent=key||' ';b.style.setProperty('--key-width',config.w||1);const isLetter=/^[A-Z]$/.test(key);if(isLetter){b.dataset.key=key;b.setAttribute('aria-label',`Select ${key}`);b.addEventListener('click',()=>selectKey(key))}else{b.classList.add('utility-key');b.tabIndex=-1;b.setAttribute('aria-hidden','true')}rowElement.appendChild(b)});grid.appendChild(rowElement)});
function finishBoot(){bootNumber.textContent='100';bootProgress.style.width='100%';bootMessage.textContent='SYSTEM READY';setTimeout(()=>{bootLayer.classList.add('finished');document.querySelector('.base').classList.add('waking');systemReady=true;track('laptop_boot_complete')},220)}
function boot(){const seen=sessionStorage.getItem('prakash_os_booted');if(seen||matchMedia('(prefers-reduced-motion: reduce)').matches){document.body.classList.add('skip-intro');finishBoot();return}document.body.classList.add('booting');const values=[0,25,50,75,100];values.forEach((value,index)=>setTimeout(()=>{bootNumber.textContent=value;bootProgress.style.width=`${value}%`;if(value===100){sessionStorage.setItem('prakash_os_booted','1');finishBoot()}},620+index*260))}
document.querySelectorAll('.suggestions button').forEach(b=>b.addEventListener('click',()=>selectKey(b.dataset.key)));
document.addEventListener('keydown',e=>{if(e.metaKey||e.ctrlKey||e.altKey||e.repeat)return;if(/^[a-z]$/i.test(e.key))selectKey(e.key)});
action.addEventListener('click',()=>track(action.dataset.event||'screen_action_click',{selected_key:display.textContent}));
document.querySelectorAll('.track-whatsapp').forEach(a=>a.addEventListener('click',()=>track('whatsapp_click',{placement:a.closest('.mobile-contact')?'mobile_bar':'page'})));
document.querySelectorAll('.track-call').forEach(a=>a.addEventListener('click',()=>track('call_click',{placement:a.closest('.mobile-contact')?'mobile_bar':'page'})));
function showDesktop(){content.classList.remove('active');desktop.classList.remove('hidden-desktop');osWindow.classList.remove('open');osWindow.style.transform='';document.querySelectorAll('[data-key]').forEach(b=>b.classList.remove('active'));track('desktop_home')}
function openApp(name){if(!systemReady||!apps[name])return;const app=apps[name];content.classList.remove('active');desktop.classList.remove('hidden-desktop');windowTitle.textContent=app.title;windowBody.innerHTML=app.html;osWindow.classList.add('open');osWindow.style.transform='';track('os_app_open',{app:name});windowBody.querySelectorAll('[data-service]').forEach(button=>button.addEventListener('click',()=>selectKey(button.dataset.service)));windowBody.querySelectorAll('[data-project]').forEach(link=>link.addEventListener('click',()=>track('project_view',{project:link.dataset.project})));windowBody.querySelectorAll('[data-contact]').forEach(link=>link.addEventListener('click',()=>track(link.dataset.contact==='call'?'call_click':'whatsapp_click',{placement:'contact_app'})))}
document.querySelectorAll('[data-app]').forEach(button=>button.addEventListener('click',()=>openApp(button.dataset.app)));
document.querySelector('#desktopHome').addEventListener('click',showDesktop);
document.querySelector('#windowClose').addEventListener('click',()=>osWindow.classList.remove('open'));
windowBody.addEventListener('click',event=>{if(event.target.closest('[data-service]')){desktop.classList.add('hidden-desktop');osWindow.classList.remove('open');content.classList.add('active')}});
grid.addEventListener('click',event=>{if(event.target.closest('[data-key]')){desktop.classList.add('hidden-desktop');osWindow.classList.remove('open');content.classList.add('active')}});
document.addEventListener('keydown',event=>{if(/^[a-z]$/i.test(event.key)&&systemReady){desktop.classList.add('hidden-desktop');osWindow.classList.remove('open');content.classList.add('active')}if(event.key==='Escape'&&systemReady)showDesktop()});
let drag=null;windowBar.addEventListener('pointerdown',event=>{if(event.target.closest('button'))return;const rect=osWindow.getBoundingClientRect();drag={x:event.clientX,y:event.clientY,left:rect.left,top:rect.top};windowBar.setPointerCapture(event.pointerId)});windowBar.addEventListener('pointermove',event=>{if(!drag)return;const dx=event.clientX-drag.x,dy=event.clientY-drag.y;osWindow.style.transform=`translate(${dx}px,${dy}px)`});windowBar.addEventListener('pointerup',()=>drag=null);windowBar.addEventListener('pointercancel',()=>drag=null);
boot();
})();
