(()=>{
  'use strict';
  const $=(s,c=document)=>c.querySelector(s), $$=(s,c=document)=>[...c.querySelectorAll(s)];
  const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
  const coarse=matchMedia('(pointer: coarse)').matches;
  const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
  const lerp=(a,b,t)=>a+(b-a)*t;
  const track=(event,params={})=>{window.dataLayer=window.dataLayer||[];window.dataLayer.push({event,...params});if(typeof window.gtag==='function')window.gtag('event',event,params);try{const key='pr_conversion_events';const data=JSON.parse(localStorage.getItem(key)||'[]');data.push({event,...params,at:new Date().toISOString()});localStorage.setItem(key,JSON.stringify(data.slice(-100)))}catch{}};
  window.trackConversion=track;
  $$('.track').forEach(el=>el.addEventListener('click',()=>track(el.dataset.event||'cta_click',{location:el.dataset.location||'',project:el.dataset.project||''})));

  document.body.classList.add('loading');
  const loader=$('.loader'), count=$('.loader-count'), bar=$('.loader-line i'), loaderName=$('.loader-name'), loaderCopy=$('.loader p');
  const returning=sessionStorage.getItem('pr_intro_seen');
  if(reduced){loader?.remove();document.body.classList.remove('loading');document.body.classList.add('ready')}
  else{const steps=returning?[100]:[0,25,50,75,100];let i=0;const next=()=>{const value=steps[i++];count.textContent=value;bar.style.width=value+'%';if(i<steps.length)setTimeout(next,returning?40:105);else{loaderName.style.cssText='opacity:1;transform:none;transition:.45s ease';loaderCopy.style.cssText='opacity:1;transition:.45s ease .1s';setTimeout(()=>{loader.classList.add('done');document.body.classList.remove('loading');document.body.classList.add('ready');sessionStorage.setItem('pr_intro_seen','1')},returning?120:620)}};next()}

  const io=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('in');io.unobserve(e.target)}}),{threshold:.14});$$('.reveal').forEach(el=>io.observe(el));
  const split=$('.split-text');if(split){split.innerHTML=split.textContent.trim().split(/\s+/).map(w=>`<span class="word">${w}</span>`).join(' ');const words=$$('.word',split);const wordIO=new IntersectionObserver(([e])=>{if(!e.isIntersecting)return;words.forEach((w,i)=>setTimeout(()=>w.classList.add('lit'),i*65));wordIO.disconnect()},{threshold:.35});wordIO.observe(split)}

  const cursor=$('.cursor');let mx=innerWidth/2,my=innerHeight/2,cx=mx,cy=my;
  if(!coarse&&cursor){addEventListener('mousemove',e=>{mx=e.clientX;my=e.clientY;cursor.style.opacity='1'});$$('[data-cursor]').forEach(el=>{el.addEventListener('mouseenter',()=>{cursor.classList.add('has-label');cursor.firstElementChild.textContent=el.dataset.cursor});el.addEventListener('mouseleave',()=>cursor.classList.remove('has-label'))});const cursorLoop=()=>{cx=lerp(cx,mx,.18);cy=lerp(cy,my,.18);cursor.style.transform=`translate(${cx}px,${cy}px) translate(-50%,-50%)`;requestAnimationFrame(cursorLoop)};cursorLoop()}
  if(!coarse&&!reduced){$$('.magnetic').forEach(el=>{el.addEventListener('mousemove',e=>{const r=el.getBoundingClientRect();el.style.transform=`translate(${(e.clientX-r.left-r.width/2)*.16}px,${(e.clientY-r.top-r.height/2)*.16}px)`});el.addEventListener('mouseleave',()=>el.style.transform='')})}

  const setupCanvas=(canvas,play=false)=>{if(!canvas||reduced)return;const ctx=canvas.getContext('2d');let w,h,dpr,points=[],pointer={x:-999,y:-999,active:false};const resize=()=>{dpr=Math.min(devicePixelRatio,1.5);w=canvas.clientWidth;h=canvas.clientHeight;canvas.width=w*dpr;canvas.height=h*dpr;ctx.setTransform(dpr,0,0,dpr,0,0);const count=play?Math.min(90,Math.floor(w/10)):Math.min(75,Math.floor(w/18));points=Array.from({length:count},()=>({x:Math.random()*w,y:Math.random()*h,vx:(Math.random()-.5)*.35,vy:(Math.random()-.5)*.35,r:Math.random()*2+1}))};const move=e=>{const r=canvas.getBoundingClientRect(),p=e.touches?.[0]||e;pointer.x=p.clientX-r.left;pointer.y=p.clientY-r.top;pointer.active=true};canvas.addEventListener('pointermove',move);canvas.addEventListener('pointerleave',()=>pointer.active=false);canvas.addEventListener('touchmove',move,{passive:true});new ResizeObserver(resize).observe(canvas);resize();let visible=true;new IntersectionObserver(([e])=>visible=e.isIntersecting,{rootMargin:'100px'}).observe(canvas);const words=['CREATE','DESIGN','BUILD','GROW'];let wi=0,lastWord=0;const draw=t=>{if(visible){ctx.clearRect(0,0,w,h);points.forEach((p,i)=>{if(pointer.active){const dx=pointer.x-p.x,dy=pointer.y-p.y,d=Math.hypot(dx,dy);if(d<150&&d>2){const force=(150-d)/150*(play?.11:.045);p.vx+=dx/d*force;p.vy+=dy/d*force}}p.vx*=.985;p.vy*=.985;p.x+=p.vx;p.y+=p.vy;if(p.x<0||p.x>w)p.vx*=-1;if(p.y<0||p.y>h)p.vy*=-1;ctx.beginPath();ctx.fillStyle=play?'rgba(255,91,68,.9)':'rgba(255,255,255,.5)';ctx.arc(p.x,p.y,p.r,0,Math.PI*2);ctx.fill();if(!play)for(let j=i+1;j<points.length;j++){const q=points[j],d=Math.hypot(p.x-q.x,p.y-q.y);if(d<105){ctx.beginPath();ctx.strokeStyle=`rgba(255,255,255,${(1-d/105)*.12})`;ctx.moveTo(p.x,p.y);ctx.lineTo(q.x,q.y);ctx.stroke()}}});if(play&&pointer.active){if(t-lastWord>900){wi=(wi+1)%words.length;lastWord=t}ctx.font=`800 ${clamp(w*.095,46,120)}px Manrope`;ctx.textAlign='center';ctx.fillStyle='rgba(247,246,241,.9)';ctx.fillText(words[wi],pointer.x,pointer.y);ctx.textAlign='left'}}requestAnimationFrame(draw)};requestAnimationFrame(draw)};
  setupCanvas($('#hero-canvas'));setupCanvas($('#play-canvas'),true);

  const scratch=$('#scratch-canvas'),scratchCard=$('.scratch-card'),scratchButton=$('.scratch-access');
  if(scratch&&scratchCard){
    const ctx=scratch.getContext('2d',{willReadFrequently:true});let drawing=false,revealed=false,moves=0,painted=false;
    const paint=()=>{const r=scratchCard.getBoundingClientRect(),dpr=Math.min(devicePixelRatio,2);scratch.width=Math.round(r.width*dpr);scratch.height=Math.round(r.height*dpr);scratch.style.width=r.width+'px';scratch.style.height=r.height+'px';ctx.setTransform(dpr,0,0,dpr,0,0);const g=ctx.createLinearGradient(0,0,r.width,r.height);g.addColorStop(0,'#202020');g.addColorStop(.5,'#777');g.addColorStop(1,'#181818');ctx.fillStyle=g;ctx.fillRect(0,0,r.width,r.height);ctx.globalAlpha=.28;for(let i=0;i<160;i++){ctx.fillStyle=i%2?'#fff':'#000';ctx.fillRect(Math.random()*r.width,Math.random()*r.height,Math.random()*36+4,1)}ctx.globalAlpha=1;ctx.fillStyle='#fff';ctx.textAlign='center';ctx.font=`800 ${Math.min(34,r.width*.06)}px Manrope`;ctx.fillText('A PRIVATE OFFER IS HIDING HERE',r.width/2,r.height/2-18);ctx.font='500 12px DM Mono';ctx.fillText('SCRATCH WITH YOUR FINGER OR MOUSE',r.width/2,r.height/2+20);ctx.globalCompositeOperation='destination-out';painted=true};
    const reveal=source=>{if(revealed)return;revealed=true;scratchCard.classList.add('revealed');scratchButton.textContent='OFFER REVEALED — CLAIM IT ABOVE';scratchButton.disabled=true;track('offer_revealed',{location:'scratch_card',method:source})};
    const coverage=()=>{const data=ctx.getImageData(0,0,scratch.width,scratch.height).data;let clear=0,total=0;for(let i=3;i<data.length;i+=64){total++;if(data[i]===0)clear++}if(clear/total>.55)reveal('scratch')};
    const scratchAt=e=>{if(!drawing||revealed)return;e.preventDefault();const r=scratch.getBoundingClientRect();ctx.beginPath();ctx.arc(e.clientX-r.left,e.clientY-r.top,coarse?32:25,0,Math.PI*2);ctx.fill();moves++;if(moves%9===0)coverage()};
    scratch.addEventListener('pointerdown',e=>{drawing=true;scratch.setPointerCapture(e.pointerId);scratchCard.classList.add('started');scratchAt(e)});scratch.addEventListener('pointermove',scratchAt);scratch.addEventListener('pointerup',()=>{drawing=false;coverage()});scratch.addEventListener('pointercancel',()=>drawing=false);scratchButton?.addEventListener('click',()=>reveal('accessible_button'));new ResizeObserver(()=>{if(!painted&&!revealed)paint()}).observe(scratchCard);paint();
  }

  $$('.service-item').forEach(item=>{const activate=()=>{$$('.service-item').forEach(i=>i.classList.remove('active'));item.classList.add('active')};item.addEventListener('mouseenter',activate);item.addEventListener('click',activate);item.addEventListener('focus',activate)});

  const showreel=$('.showreel'), shell=$('.video-shell'), video=$('#showreel-video'), toggle=$('.video-toggle');let videoTracked=false;
  const updateShowreel=()=>{if(!showreel||reduced)return;const r=showreel.getBoundingClientRect(),max=showreel.offsetHeight-innerHeight,p=clamp(-r.top/max,0,1);const scale=lerp(1,Math.max(innerWidth/(shell.offsetWidth||1),innerHeight/(shell.offsetHeight||1))*1.03,p);shell.style.transform=`scale(${scale})`;if(p>.28&&p<.92){video.play().then(()=>{toggle.textContent='PAUSE';if(!videoTracked){track('showreel_play',{location:'scroll'});videoTracked=true}}).catch(()=>{})}else if(p>=.92||p<.12){video.pause();toggle.textContent='PLAY'}};addEventListener('scroll',updateShowreel,{passive:true});updateShowreel();
  toggle?.addEventListener('click',()=>{if(video.paused){video.play();toggle.textContent='PAUSE';track('showreel_play',{location:'button'})}else{video.pause();toggle.textContent='PLAY'}});

  if(!coarse&&!reduced){$$('.project-canvas,[data-tilt]').forEach(el=>{el.addEventListener('mousemove',e=>{const r=el.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;el.style.transform=`perspective(900px) rotateY(${x*7}deg) rotateX(${-y*7}deg)`});el.addEventListener('mouseleave',()=>el.style.transform='')})}

  const dragWindow=$('.testimonial-window'),dragTrack=$('.testimonial-track');if(dragWindow&&dragTrack){let down=false,start=0,current=0,origin=0;const max=()=>Math.max(0,dragTrack.scrollWidth-innerWidth*.9);const render=()=>dragTrack.style.transform=`translate3d(${-current}px,0,0)`;dragWindow.addEventListener('pointerdown',e=>{down=true;start=e.clientX;origin=current;dragWindow.setPointerCapture(e.pointerId)});dragWindow.addEventListener('pointermove',e=>{if(!down)return;current=clamp(origin-(e.clientX-start),0,max());render()});const stop=()=>down=false;dragWindow.addEventListener('pointerup',stop);dragWindow.addEventListener('pointercancel',stop)}

  let lastY=scrollY,velocity=0;const marqueeEls=$$('.marquee div');addEventListener('scroll',()=>{velocity=scrollY-lastY;lastY=scrollY;marqueeEls.forEach(el=>el.style.animationDuration=clamp(22-Math.abs(velocity)*.15,8,22)+'s')},{passive:true});

  const engage=$('.engage');const dismiss=()=>{engage.hidden=true;sessionStorage.setItem('pr_engage_seen','1')};$('.engage-close')?.addEventListener('click',()=>{track('engagement_dismiss',{location:'20_second'});dismiss()});$$('.engage-options button').forEach(btn=>btn.addEventListener('click',()=>{track('engagement_selection',{selection:btn.dataset.need});dismiss();open(`https://wa.me/917397559527?text=${encodeURIComponent(`Hi Prakash, I need ${btn.dataset.need}. Please tell me how you can help.`)}`,'_blank','noopener')}));if(!sessionStorage.getItem('pr_engage_seen'))setTimeout(()=>{engage.hidden=false;track('engagement_view',{location:'20_second'})},20000);
})();
