(() => {
  const sources={indeed:'https://in.indeed.com/q-digital-marketing-l-puducherry-jobs.html',linkedin:'https://in.linkedin.com/jobs/digital-marketing-executive-jobs-puducherry',simply:'https://www.simplyhired.co.in/search?l=puducherry%2C+puducherry&q=digital+marketing'};
  const jobs=[
    {type:'CREATIVE',pay:'CHECK SOURCE',title:'AI Digital Content Creator',company:'Valvenet Technologies',summary:'Create AI-assisted photos, videos and social content for web campaigns.',skills:['AI Content','Video','Social Media'],interview:'Show examples of posters, videos or prompts. Explain how you maintain brand consistency and verify AI-generated content.',source:'indeed'},
    {type:'PART-TIME',pay:'₹500–₹50K',title:'Marketing',company:'yasaircon',summary:'Flexible marketing support with work-from-home possibilities.',skills:['Communication','Lead Generation','Follow-up'],interview:'Prepare examples of prospecting, customer communication and how you would convert an enquiry into a lead.',source:'indeed'},
    {type:'FULL-TIME',pay:'CHECK SOURCE',title:'Junior Admin & Business Development Executive',company:'Valvenet Technologies',summary:'Support administration, outreach and business-development activity.',skills:['Business Development','Admin','Communication'],interview:'Expect questions on follow-ups, reporting, prospect handling, organisation and willingness to learn.',source:'indeed'},
    {type:'FULL-TIME',pay:'₹20K–₹25K',title:'Real Estate Marketing Manager',company:'Sadhisha Homes',summary:'Plan campaigns and generate qualified property leads.',skills:['Lead Generation','Campaigns','Project Management'],interview:'Prepare a property lead funnel, monthly campaign plan, channel budget and lead follow-up process.',source:'simply'},
    {type:'FULL-TIME',pay:'CHECK SOURCE',title:'Marketing Manager',company:'Super Pro Retail Guru',summary:'Manage digital and field-marketing activity for customer acquisition.',skills:['Field Marketing','Digital Marketing','Acquisition'],interview:'Be ready with a local customer-acquisition plan, campaign measurement approach and team coordination examples.',source:'indeed'},
    {type:'0–3 YEARS',pay:'CHECK SOURCE',title:'Marketing Executive',company:'Super Pro Retail Guru',summary:'Execute field and digital campaigns to acquire customers.',skills:['Marketing','Sales','Customer Acquisition'],interview:'Prepare prospecting methods, campaign ideas, objection handling and examples of working toward a target.',source:'indeed'},
    {type:'SOCIAL MEDIA',pay:'CHECK SOURCE',title:'Social Media Marketer',company:'Bestea',summary:'Engage customers across Facebook and other social platforms.',skills:['Facebook','Engagement','Community'],interview:'Show how you reply to comments, manage complaints, improve engagement and plan content for a local brand.',source:'indeed'},
    {type:'INTERNSHIP',pay:'₹1K–₹5K',title:'Digital Marketing Intern',company:'Aakhaash Institute of Media Studies',summary:'Gain practical experience through live digital-marketing projects.',skills:['Social Media','Content','Digital Basics'],interview:'Know basic SEO, social media, Canva and campaign terminology. Carry one sample content calendar.',source:'simply'},
    {type:'FULL-TIME',pay:'CHECK SOURCE',title:'Social Media Marketing Executive',company:'ABM Groups / BM Academy',summary:'Coordinate social activity with marketing and design teams.',skills:['Social Strategy','Coordination','Content'],interview:'Prepare a monthly content plan and explain how you coordinate designers, approvals, publishing and reporting.',source:'indeed'},
    {type:'FRESHER',pay:'CHECK SOURCE',title:'SEO / SEM Developer',company:'XenAI Tech',summary:'Support search optimisation and paid-search execution.',skills:['SEO','SEM','Keywords','Analytics'],interview:'Revise keyword research, on-page SEO, Google Ads basics, campaign metrics and landing-page relevance.',source:'linkedin'},
    {type:'CREATIVE',pay:'CHECK SOURCE',title:'Digital Media Designer & Video Editor',company:'XenAI Tech',summary:'Design campaign visuals and edit digital video content.',skills:['Design','Video Editing','Social Content'],interview:'Bring a portfolio or showreel and explain editing workflow, design decisions, revision handling and platform formats.',source:'linkedin'},
    {type:'CREATIVE',pay:'CHECK SOURCE',title:'Graphic Designer',company:'DigitalTechz',summary:'Create brand and marketing visuals for digital channels.',skills:['Graphic Design','Typography','Branding'],interview:'Present 4–6 strong designs. Explain hierarchy, colour, typography, brief interpretation and export preparation.',source:'linkedin'},
    {type:'PRODUCT',pay:'CHECK SOURCE',title:'Product Marketing Manager',company:'DrDoctor',summary:'Position a B2B SaaS product for complex buying journeys.',skills:['B2B SaaS','Positioning','Go-to-market'],interview:'Prepare positioning, customer research, launch planning, sales enablement and product-marketing measurement examples.',source:'linkedin'},
    {type:'WEB',pay:'CHECK SOURCE',title:'Junior WordPress Developer',company:'HyperZ Digital',summary:'Build and maintain marketing-focused WordPress websites.',skills:['WordPress','Web Design','SEO'],interview:'Revise themes, plugins, responsive layouts, page speed, basic SEO and examples of websites you have built.',source:'linkedin'}
  ];
  const grid=document.querySelector('.job-grid');
  jobs.forEach(job=>{
    const card=document.createElement('article');
    card.innerHTML=`<div class="job-meta"><span>${job.type}</span><span>${job.pay}</span></div><h3>${job.title}</h3><h4>${job.company}</h4><p>${job.summary}</p><div class="skills">${job.skills.map(skill=>`<span>${skill}</span>`).join('')}</div><details><summary>Interview preparation</summary><p>${job.interview}</p></details><a href="${sources[job.source]}" target="_blank" rel="noopener">VIEW SOURCE ↗</a>`;
    grid.appendChild(card);
  });
})();
