import Image from 'next/image';
import { AdmissionCheck, ConversionBars, CRMDemo, CTA, Navigation, SchoolDemo } from '@/components/interactive';
import { contact } from '@/lib/config';

function Heading({label,title,children}:{label:string;title:string;children?:React.ReactNode}){return <div className="section-heading"><p className="eyebrow">{label}</p><h2>{title}</h2>{children && <p className="section-desc">{children}</p>}</div>;}
const engine = [
 ['01','Google + Local SEO','Help local parents discover your school when they search nearby.'],
 ['02','Instagram + Facebook','Build familiarity and trust before a parent contacts you.'],
 ['03','Reels + Content','Show your classrooms, teachers and the real school experience.'],
 ['04','Website','Give parents clear reasons to choose you and a simple way to enquire.'],
 ['05','Meta Ads','Reach relevant local parents during admission periods.'],
 ['06','WhatsApp','Make starting a conversation easy and welcoming.'],
 ['07','Admission CRM','Keep every enquiry, visit and follow-up in one place.'],
 ['08','AI + Automation','Respond faster and reduce repetitive work, with staff in control.'],
 ['09','Analytics','Understand which activities are generating enquiries.']
];
const aiCards = [
 ['01','AI Admission Assistant','Parents get answers from school-approved information.', ['Accepted ages and school timings','Transport availability','Booking visits and contacting admissions']],
 ['02','AI + WhatsApp Support','Give a quick first response before your staff personally continue the conversation.', ['Common admission FAQs','Enquiry routing to the right person','Hand over important questions to staff']],
 ['03','AI Follow-up Assistant','Help your team see which parents need attention.', ['New enquiries and follow-up due','Visits not scheduled or completed','Parents waiting for a response']],
 ['04','AI Content Assistant','Spend less time staring at an empty content calendar.', ['Reel ideas and captions','Parent education and admission posts','Monthly calendars and event content']],
 ['05','AI Creative Studio','Create useful school content with AI-assisted production.', ['Posters and promotional creatives','Videos, Reels and voiceovers','School review before publication']],
 ['06','AI Admission Insights','Ask useful questions when connected to reliable, authorised CRM data.', ['How many enquiries came this month?','How many visits are scheduled?','Which source generated enquiries?']]
];
const content = ['A Day at Our Preschool','Meet Our Teachers','Classroom Activities','Learning Through Play','Parent Testimonials','Campus Tour','School Celebrations','Parenting Tips','Admission FAQs','Why Parents Choose Us','Student Activities','Admission Campaigns'];
const fixes = [ ['Website but few enquiries?','Website conversion optimisation'],['Instagram inactive?','Social media + Reels'],['Need more local enquiries?','Meta Ads + local campaigns'],['Poor Google visibility?','Local SEO'],['Enquiries getting forgotten?','Admission CRM'],['Slow responses?','WhatsApp + automation'],['Too much repetitive work?','AI automation'],["No idea what’s working?",'Analytics + reporting'] ];
const faqs = [
 ['Do I need a new website?','Not necessarily. If your existing website is good, we can improve its enquiry and conversion journey rather than rebuild it.'],
 ['Can you manage Instagram and Facebook?','Yes, including strategy, content ideas, creatives, Reels and admission-focused campaigns, depending on the engagement we agree on.'],
 ['Can you run Meta Ads?','Yes. Campaigns can focus on reaching relevant local audiences and generating enquiries or school visits. Advertising spend and campaign scope are agreed separately.'],
 ['Can you build an admission CRM?','Yes. A simple system can help your school track enquiries, follow-ups, visits and admission status.'],
 ['Can AI answer parent questions?','Yes, when properly configured using approved school information. Sensitive or important matters should still be escalated to staff.'],
 ['Can AI automatically run my whole school?','No. AI is an assistant for repetitive work, information retrieval, content, enquiry handling and operational support. Teachers and school leadership remain in charge.'],
 ['Do you work with schools in Pondicherry and Chennai?','Yes. I work with schools and preschools in Pondicherry / Puducherry and Chennai. Start by sending your school name and location on WhatsApp.']
];
export default function Home(){return <>
<Navigation/>
<main id="main">
<section className="hero" id="top"><div className="container hero-grid"><div className="hero-copy"><p className="eyebrow"><span className="location-line"/> PONDICHERRY · CHENNAI</p><h1>More parents<br/> should know<br/> about <span>your school.</span></h1><p className="hero-desc">I build digital admission systems that help local parents discover your school, trust it, enquire, book a visit and stay connected through better follow-up.</p><div className="hero-actions"><CTA location="hero">Get my free school digital audit</CTA><CTA location="hero" kind="call" secondary>Call Prakash</CTA></div><div className="hero-trust"><span className="trust-symbol">✦</span> 14+ years in Digital, SEO, Web & Growth</div></div>
<div className="hero-visual with-image"><div className="hero-image-wrap engine-image-wrap"><Image src="/images/admission-engine.svg" alt="School Admission Engine: website, Google, social content and ads connect to WhatsApp, CRM and AI follow-up, creating school visits and admission opportunities" width={520} height={430} sizes="(max-width: 800px) 90vw, 520px" priority/></div><div className="visual-title"><span>SCHOOL ADMISSION ENGINE</span><span className="ai-badge">+ AI</span></div><div className="journey-preview"><div className="preview-step"><span className="step-icon">01</span><div><strong>A parent starts searching</strong><small>“A good preschool near me”</small></div></div><div className="preview-connector"/><div className="preview-step"><span className="step-icon coral">02</span><div><strong>Your school gets discovered</strong><small>Google · Instagram · Facebook</small></div></div><div className="preview-connector"/><div className="preview-step"><span className="step-icon lavender">03</span><div><strong>Trust becomes a conversation</strong><small>School website · Reviews · WhatsApp</small></div></div><div className="preview-connector"/><div className="preview-step final"><span className="step-icon">04</span><div><strong>A school visit. A new possibility.</strong><small>Follow-up · Admission opportunity</small></div></div></div><div className="visual-note"><span>✦</span><p>Every step connected.<br/><strong>Every enquiry given attention.</strong></p></div></div>
</div><div className="channel-strip container"><span>ONE CONNECTED SYSTEM</span><p>Website <b>·</b> Google <b>·</b> Instagram <b>·</b> Facebook <b>·</b> Meta Ads <b>·</b> WhatsApp <b>·</b> CRM <b>·</b> AI Automation</p></div></section>
<section className="section problem"><div className="container split"><Heading label="THE REAL PROBLEM" title="Your school may be good. But do enough parents know it?">Parents searching for schools nearby may compare your website, photos, reviews and social media before they call. Make that first impression count.</Heading><div><div className="parent-search"><span className="search-icon">⌕</span> What does a parent see about your school?</div><div className="trust-grid">{['Google presence','Website','Instagram','Photos & activities','Facilities','Genuine reviews','Parent testimonials','Clear communication','Easy contact'].map(x=><span key={x}>{x}</span>)}</div><p>If your online presence does not build trust or make enquiry easy, some parents may move on to another school.</p><CTA location="problem">Check my school for free</CTA></div></div></section>
<section className="section tinted" id="check"><div className="container"><Heading label="A SIMPLE SELF-CHECK" title="Where could your school be losing admission opportunities?">Ten practical questions. A clearer starting point.</Heading><AdmissionCheck/></div></section>
<section className="section journey-section"><div className="container"><Heading label="THINK LIKE A PARENT" title="How a parent can become an admission enquiry">More discovery → More trust → More enquiries → Better follow-up → More admission opportunities.</Heading><ol className="parent-journey">{['Google search','Instagram / Facebook','School website','Reviews + trust','WhatsApp / call','Follow-up','School visit','Admission opportunity'].map((x,i)=><li key={x}><span>{String(i+1).padStart(2,'0')}</span><strong>{x}</strong></li>)}</ol><div className="section-bottom"><p>I help connect this entire journey.</p><CTA location="journey">Show me what I’m missing</CTA></div></div></section>
<section className="section engine-section" id="engine"><div className="container"><Heading label="SCHOOL ADMISSION ENGINE + AI" title="Not just digital marketing. A complete school admission engine.">Your channels should work together towards a meaningful next step: a parent conversation and a school visit.</Heading><div className="grid-three engine-grid">{engine.map(([num,title,desc])=><article className="card engine-card" key={title}><span className="card-number">{num}</span><h3>{title}</h3><p>{desc}</p></article>)}</div><div className="engine-outcome"><span>ALL WORKING TOWARDS</span><h3>School visits & admission opportunities</h3><p>Build the right foundations. Follow up. Measure what works.</p></div><div className="center-cta"><CTA location="engine">Improve my admission system</CTA></div></div></section>
<section className="section ai-section" id="ai"><div className="container"><div className="ai-heading-row"><Heading label="A SMARTER SCHOOL TEAM" title="Don’t just digitally market your school. Make it AI-ready.">Marketing helps parents discover your school. AI can help your team respond faster, follow up better and reduce repetitive work.</Heading><figure className="ai-illustration"><Image src="/images/school-ai.webp" alt="Illustration of a school administrator using AI-assisted tools with staff in control" width={1200} height={800} sizes="(max-width: 800px) 90vw, 360px"/><figcaption>Practical support. Your team stays in control.</figcaption></figure></div><div className="grid-three ai-grid">{aiCards.map(([num,title,desc,items])=><article className="card ai-card" key={title as string}><span className="card-number">{num}</span><h3>{title}</h3><p>{desc}</p><ul>{(items as string[]).map(x=><li key={x}>{x}</li>)}</ul></article>)}</div><div className="ai-rule"><span>✦</span><p><strong>Your school’s information. Your school’s control.</strong><br/>AI answers must come from authorised school data. Staff approve the information and take over sensitive or important conversations.</p></div></div></section>
<section className="section ask-section"><div className="container split"><div><Heading label="ASK YOUR SCHOOL" title="Imagine asking your school like ChatGPT.">Less searching through notebooks and chat histories. More clarity on enquiries, follow-ups and visits.</Heading><p className="demo-disclaimer">Demo example. Actual answers depend on the school’s connected and authorised data.</p><CTA location="school-demo" kind="ai">I want to make my school AI-ready</CTA></div><SchoolDemo/></div></section>
<section className="section tinted" id="crm"><div className="container"><Heading label="KEEP EVERY OPPORTUNITY IN VIEW" title="A lead is not an admission.">Enquiries need organised follow-up. Know exactly which parents need attention instead of losing enquiries inside calls, notebooks or WhatsApp chats.</Heading><div className="pipeline">{['New Enquiry','Contacted','Interested','Visit Scheduled','Visited','Follow-up','Admitted'].map((x,i)=><span key={x}><b>{i+1}</b>{x}</span>)}</div><CRMDemo/><div className="section-bottom"><p>A practical system your admission team can use.</p><CTA location="crm" message="Hi Prakash, I manage a school/preschool in ______. I would like a free audit of our admission enquiry and follow-up process, and to discuss a simple admission CRM.">Help organise my enquiries</CTA></div></div></section>
<section className="section content-section"><div className="container"><Heading label="CONTENT WITH A PURPOSE" title="What will we actually post?">The goal is not simply to post every day. Show parents what makes your school worth a visit.</Heading><div className="content-gallery"><article className="content-photo-card"><Image src="/images/classroom-play.webp" alt="Illustration of a teacher guiding preschool children learning through play" width={1200} height={800} sizes="(max-width: 650px) 90vw, 380px"/><div><span className="eyebrow">SHOW THE EXPERIENCE</span><h3>Let parents see school life.</h3><p>Activities, teachers, classroom moments and learning through play.</p></div></article><article className="content-photo-card"><Image src="/images/school-visit.webp" alt="Illustration of a welcoming parent and teacher conversation" width={1200} height={800} sizes="(max-width: 650px) 90vw, 380px"/><div><span className="eyebrow">BUILD PARENT CONFIDENCE</span><h3>Make your school feel familiar.</h3><p>Campus tours, genuine parent stories and what makes your school special.</p></div></article><article className="content-photo-card"><Image src="/images/school-ai.webp" alt="Illustration of school staff organising helpful admission information" width={1200} height={800} sizes="(max-width: 650px) 90vw, 380px"/><div><span className="eyebrow">START CONVERSATIONS</span><h3>Answer what parents ask.</h3><p>Admission FAQs, parenting tips and clear invitations to visit.</p></div></article></div><p className="illustration-note">Illustrative visuals. Your school’s content would use approved school photos, videos and information.</p><div className="content-topic-chips">{content.map(x=><span key={x}>{x}</span>)}</div><div className="content-purpose"><span>See the school</span><span>Understand the school</span><span>Trust the school</span><span>Contact the school</span></div></div></section>
<section className="section comparison"><div className="container"><Heading label="THE ONLINE FIRST IMPRESSION" title="When a parent compares two schools online…">An illustrative comparison of fictional schools. These are not real competitor findings.</Heading><div className="comparison-grid"><article className="comparison-card"><p className="eyebrow">FICTIONAL SCHOOL A</p><h3>Harder to get to know.</h3><ul>{['Poor or outdated website','Inactive Instagram','Limited recent photos','Limited reviews','WhatsApp hard to find','School visit button missing'].map(x=><li key={x}><span aria-hidden="true">−</span>{x}</li>)}</ul></article><article className="comparison-card better"><p className="eyebrow">FICTIONAL SCHOOL B</p><h3>Clear. Visible. Welcoming.</h3><ul>{['Modern, useful website','Active Instagram','Real school content','Strong genuine Google reviews','WhatsApp easy to find','Clear book-a-visit button'].map(x=><li key={x}><span aria-hidden="true">✓</span>{x}</li>)}</ul></article></div><div className="section-bottom"><h3>Which school builds trust faster?</h3><CTA location="comparison">Check my school’s first impression</CTA></div></div></section>
<section className="section"><div className="container"><Heading label="ALREADY HAVE A WEBSITE?" title="You don’t need to start from zero.">We improve what’s missing instead of forcing you to rebuild everything.</Heading><div className="fixes-grid">{fixes.map(([problem,solution])=><article key={problem}><p>{problem}</p><h3>{solution}</h3></article>)}</div></div></section>
<section className="section audit-section" id="audit"><div className="container audit-grid"><div><span className="pill">FREE SCHOOL DIGITAL ADMISSION AUDIT</span><h2>Don’t hire me yet.</h2><p className="audit-sub">Let me first show you<br/>what can be improved.</p><p>Send your school name and location. I’ll review your current digital admission journey and explain the most useful improvements in simple language.</p><CTA location="audit">Audit my school free</CTA><p className="small">Start on WhatsApp. Decide what’s worth improving afterwards.</p></div><div className="audit-paper"><p className="eyebrow">YOUR SCHOOL · A FRESH PERSPECTIVE</p><h3>What I will review</h3><ul className="audit-list">{['Website & mobile experience','Google presence & reviews','Instagram & Facebook','Admission buttons & WhatsApp journey','School content','Local competitors','Enquiry process & follow-up','AI & automation opportunities'].map(x=><li key={x}><span>✓</span>{x}</li>)}</ul><div className="audit-output"><span>YOUR TAKEAWAY</span><strong>What’s working.</strong><strong>What’s missing.</strong><strong>What I would improve first.</strong></div></div></div></section>
<section className="section about-section" id="about"><div className="container about-grid"><div className="portrait-wrap"><Image src={contact.portrait} alt="Portrait illustration of Prakash Ravikumar" width={800} height={800} sizes="(max-width: 700px) 85vw, 360px"/><div className="portrait-caption"><strong>14+ years</strong><span>Digital, SEO, Web & Growth</span></div></div><div><Heading label="MEET YOUR DIGITAL PARTNER" title="Meet Prakash Ravikumar."/><h3 className="about-sub">Digital Marketing + Web + AI + Automation</h3><p>I have 14+ years of experience across web development, SEO, digital marketing, content, lead generation, conversion optimisation and digital growth.</p><p>Today I combine those skills with AI and automation to help businesses build smarter digital systems.</p><p>For schools, my goal is simple: help more relevant parents discover your school, make it easier for them to enquire, and give your team a better system for managing those opportunities.</p><div className="skill-chips">{['SEO','Local SEO','Web Development','Landing Pages','Social Media','Content Marketing','Reels','Meta Ads','Lead Generation','CRO','Google Analytics','CRM','WhatsApp','AI','Automation','AI Content','AI Video','AI Posters','Business Systems'].map(x=><span key={x}>{x}</span>)}</div></div></div></section>
<section className="section one-partner"><div className="container"><Heading label="CONNECTED, PRACTICAL, ADMISSION-FOCUSED" title="One partner. One admission system.">Your website, SEO, social media, ads, content, CRM, automation and AI should support the same goal.</Heading><div className="partner-channels">{['Website','SEO','Social media','Ads','Content','CRM','Automation','AI'].map(x=><span key={x}>{x}</span>)}</div><p className="partner-copy">I help connect these areas into one practical system, with a clear plan and scope. When a project needs specialist support, we agree on it together.</p><CTA location="partner" kind="call">Book a quick call</CTA></div></section>
<section className="section"><div className="container"><Heading label="HOW WE START" title="One simple first step."/><ol className="start-steps">{['Send me your school name.','I review your current digital presence.','I show you the biggest opportunities.','We decide what is worth improving.','We build and measure.'].map((x,i)=><li key={x}><span>{String(i+1).padStart(2,'0')}</span><h3>{x}</h3></li>)}</ol><div className="center-cta"><CTA location="start">Start with my free audit</CTA></div></div></section>
<section className="section faq-section" id="faq"><div className="container split"><Heading label="CLEAR ANSWERS" title="Before you get in touch…">A few things school owners often want to know.</Heading><div className="faq-list">{faqs.map(([q,a])=><details key={q}><summary>{q}<span aria-hidden="true">+</span></summary><p>{a}</p></details>)}</div></div></section>
<section className="section final-section"><div className="container"><p className="eyebrow">YOUR NEXT ADMISSION JOURNEY STARTS HERE</p><h2>More parents could be looking for a school <span>like yours.</span></h2><p>Let’s make sure they can discover you, trust you and contact you easily.</p><div className="final-actions"><CTA location="final">WhatsApp Prakash — free school audit</CTA><CTA location="final" kind="call" secondary>Call Prakash</CTA></div><p className="small">Pondicherry · Chennai</p></div></section>
</main>
<footer><div className="container footer-grid"><div><strong>Prakash Ravikumar</strong><p>Digital Admission Growth & AI Partner</p><p>Pondicherry · Chennai</p></div><div><CTA location="footer" kind="call" secondary>{contact.phoneDisplay}</CTA><CTA location="footer" kind="whatsapp">WhatsApp Prakash</CTA></div><div><a href={contact.website}>webdev-prakash.vercel.app</a><a href="/jobs.html">Marketing jobs & interview preparation</a><p className="small">© 2026 Prakash Ravikumar</p></div></div></footer>
<ConversionBars/>
</>;}
