import Image from 'next/image';
import Link from 'next/link';
import { CTA } from '@/components/interactive';
import { contact } from '@/lib/config';
export function Heading({label,title,children}:{label:string;title:string;children?:React.ReactNode}){return <div className="section-heading"><p className="eyebrow">{label}</p><h2>{title}</h2>{children && <p className="section-desc">{children}</p>}</div>;}
export const services = [
 {href:'/school-digital-marketing',title:'School Digital Marketing',desc:'Help nearby parents discover and get to know your school.',items:'Google · Social media · Reels · Meta Ads',image:'/images/classroom-play.webp'},
 {href:'/school-websites',title:'Websites & Admission Enquiries',desc:'Turn parent interest into conversations and school visits.',items:'Websites · Landing pages · WhatsApp · Visit requests',image:'/images/school-visit.webp'},
 {href:'/school-ai-automation',title:'CRM, AI & Automation',desc:'Build a practical way to organise enquiries and support your team.',items:'Follow-up · Custom CRM · AI assistants · Automation',image:'/images/school-ai.webp'}
];
export function ServiceCards(){return <section className="section" id="services"><div className="container"><Heading label="WHAT DOES YOUR SCHOOL NEED?" title="Three ways to strengthen your admission journey.">Start with the part that needs attention. Connect the rest as your school needs it.</Heading><div className="content-gallery">{services.map(s=><Link className="content-photo-card service-link" href={s.href} key={s.href}><Image src={s.image} alt="Illustrative school scene" width={1200} height={800} sizes="(max-width: 650px) 90vw, 380px"/><div><h3>{s.title}</h3><p>{s.desc}</p><p className="small service-items">{s.items}</p><strong className="service-more">Explore this service →</strong></div></Link>)}</div><p className="illustration-note">Illustrative visuals. School content uses approved photos, videos and information.</p></div></section>;}
export function PageHero({label,title,description,image}:{label:string;title:string;description:string;image:string}){return <section className="service-hero" id="top"><div className="container service-hero-grid"><div><Link className="breadcrumb" href="/">Home /</Link><p className="eyebrow">{label} · PONDICHERRY & CHENNAI</p><h1>{title}</h1><p className="hero-desc">{description}</p><div className="hero-actions"><CTA location={label}>Get my free school audit</CTA><CTA kind="call" secondary location={label}>Call Prakash</CTA></div></div><Image src={image} alt="Illustration of the school admission journey" width={1200} height={800} sizes="(max-width: 800px) 90vw, 500px" priority/></div></section>;}
export function AuditBanner(){return <section className="section audit-section"><div className="container audit-banner"><div><p className="eyebrow">START WITH CLARITY</p><h2>Let’s find what your school needs first.</h2><p>A free review of your digital presence and enquiry journey. A practical next step.</p></div><Link className="btn" href="/free-school-audit">Explore the free school audit →</Link></div></section>;}
export function Footer(){return <footer><div className="container footer-grid"><div><strong>Prakash Ravikumar</strong><p>Digital Admission Growth & AI Partner</p><p>Pondicherry · Chennai</p></div><div className="footer-pages"><Link href="/">Home</Link>{services.map(s=><Link href={s.href} key={s.href}>{s.title}</Link>)}<Link href="/free-school-audit">Free School Audit</Link></div><div><CTA location="footer" kind="call" secondary>{contact.phoneDisplay}</CTA><p><CTA location="footer">WhatsApp Prakash</CTA></p><a href="/jobs.html">Marketing jobs & interview preparation</a><p className="small">© 2026 Prakash Ravikumar</p></div></div></footer>;}
